Repository AliSandro104/LOG8100, pull requests merged in 2024-12, with the labels that each got.

#50 Feature/prometheus
  WebGoat/create.sql
  WebGoat/pom.xml
  WebGoat/src/main/resources/application-webgoat.properties
  ansible/deploy_grafana.yml
  ansible/deploy_prometheus.yml
  ansible/master.yml
Labels: enhancement

#57 Release/0.0.6
  .github/workflows/staging.yml
Labels: bug

#58 Changed the trivy production workflow template config
  .github/workflows/production.yml
Labels: bug

#60 General improvements
  ansible/deploy_grafana.yml
  ansible/deploy_ingress_controller.yml
  ansible/deploy_prometheus.yml
  ansible/deploy_webgoat.yml
  ansible/install_minikube.yml
  ansible/store/grafana/values.yml
  ansible/store/prometheus/values.yml
  systemd/monitor-port-forward.sh
  terraform/main.tf
Labels: bug, enhancement

#62 Release/0.0.6
  ansible/deploy_grafana.yml
  ansible/deploy_prometheus.yml
  ansible/install_minikube.yml
  ansible/store/grafana/resources.yml
  ansible/store/prometheus/alert_manager.yml
  ansible/store/prometheus/server.yml
  ansible/store/prometheus/server_files.yml
Labels: enhancement

#64 Release/0.0.6
  .github/workflows/delivery.yml
  .github/workflows/deployment.yml
  .github/workflows/image-scanning.yml
  .github/workflows/terraform.yml
Labels: enhancement

#66 Update delivery.yml
  .github/workflows/delivery.yml
  .github/workflows/deployment.yml
Labels: enhancement

#63 kubecost
  ansible/deploy_kubecost.yml
  ansible/master.yml
  systemd/monitor-port-forward.sh
Labels: enhancement

#67 Release/0.0.8
  ansible/deploy_kubecost.yml
  ansible/master.yml
  systemd/monitor-port-forward.sh
Labels: enhancement

#68 Fixed the ansible kubecost deployment
  ansible/deploy_kubecost.yml
  systemd/monitor-port-forward.sh
Labels: bug

#70 Updated the alerts
  ansible/store/prometheus/server_files.yml
Labels: bug, enhancement

#71 Release/0.0.10
  ansible/store/prometheus/server_files.yml
Labels: bug, enhancement

#74 Added missing inbound security rules
  terraform/main.tf
Labels: enhancement

#76 Fixed small config issues for the dependabot
  .github/dependabot.yml
  .github/dependabot_auto_approve.yml
  .github/dependabot_auto_merge.yml
Labels: bug

#77 Release/0.0.11
  .github/dependabot.yml
  .github/dependabot_auto_approve.yml
  .github/dependabot_auto_merge.yml
  README.md
  terraform/main.tf
Labels: bug, enhancement

#85 Updated the README + cleaned certain IaC files
  .github/workflows/terraform.yml
  README.md
  ansible/deploy_ingress_controller.yml
  ansible/install_minikube.yml
Labels: enhancement

#86 Release/0.1.0
  .github/workflows/checkov.yml
  .github/workflows/terraform.yml
  README.md
  ansible/deploy_ingress_controller.yml
  ansible/install_minikube.yml
Labels: enhancement
